[versions]
kotlin = "2.3.0"

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
spotless-gradlePlugin = "com.diffplug.spotless:spotless-plugin-gradle:8.1.0"
kotlinx-dateTime = "org.jetbrains.kotlinx:kotlinx-datetime:0.7.1"
ktlint = "com.pinterest.ktlint:ktlint-cli:1.8.0"
clikt = "com.github.ajalt.clikt:clikt:5.1.0"
assertk = "com.willowtreeapps.assertk:assertk:0.28.1"
okio = "com.squareup.okio:okio:3.16.4"
